language: ruby
rvm:
  - "2.3.0"
  - "2.4.0"
env:
  - DB=pgsql
services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database stockwatcher_test;' -U postgres

addons:
  postgresql: "9.6"
